language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ritusingh/docker-react -f Dockerfile.dev .

script:
  - docker run ritusingh/docker-react npm run test -- --coverage
